// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHW_zDXv_R8WOIn1f5OjLuggVFaoWkhJ0',
    appId: '1:421758830578:web:ccedb01886f8e9557e0d6b',
    messagingSenderId: '421758830578',
    projectId: 'trivia-app-a12ad',
    authDomain: 'trivia-app-a12ad.firebaseapp.com',
    storageBucket: 'trivia-app-a12ad.firebasestorage.app',
    measurementId: 'G-YBPSVF1CBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAIBMRIlBjLENP3OOldlH8Z5StkSG_cP0',
    appId: '1:421758830578:android:e8c20fe417eb9b007e0d6b',
    messagingSenderId: '421758830578',
    projectId: 'trivia-app-a12ad',
    storageBucket: 'trivia-app-a12ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrIIWxd-ufAYcA5nVGFoL_RTMPK9JqOVA',
    appId: '1:421758830578:ios:dca78d5a49206c247e0d6b',
    messagingSenderId: '421758830578',
    projectId: 'trivia-app-a12ad',
    storageBucket: 'trivia-app-a12ad.firebasestorage.app',
    iosClientId: '421758830578-0gr9jlmd1m63ef2sspke10ao9d1jv77d.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrIIWxd-ufAYcA5nVGFoL_RTMPK9JqOVA',
    appId: '1:421758830578:ios:dca78d5a49206c247e0d6b',
    messagingSenderId: '421758830578',
    projectId: 'trivia-app-a12ad',
    storageBucket: 'trivia-app-a12ad.firebasestorage.app',
    iosClientId: '421758830578-0gr9jlmd1m63ef2sspke10ao9d1jv77d.apps.googleusercontent.com',
    iosBundleId: 'com.example.triviaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHW_zDXv_R8WOIn1f5OjLuggVFaoWkhJ0',
    appId: '1:421758830578:web:193ab918442a1d557e0d6b',
    messagingSenderId: '421758830578',
    projectId: 'trivia-app-a12ad',
    authDomain: 'trivia-app-a12ad.firebaseapp.com',
    storageBucket: 'trivia-app-a12ad.firebasestorage.app',
    measurementId: 'G-1M98XK77NX',
  );
}
